server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/maxjang?autoReconnect=true
    # Set on IntelliJ Setting
    username:
    password:
  jpa:
    show-sql: true
    generate-ddl: true # Turn 'spring.jpa.hibernate.ddl-auto' on
    hibernate:
      ddl-auto: create
    open-in-view: false # For database performance
